import type { MouseLighting, MouseStatus } from "@openmouse/protocol/drivers/mouse-types";
import { PREVIEW_KEYS, type FixturePreviewMode } from "./preview-modes";

export { PREVIEW_KEYS };

/**
 * Dev-only stand-in statuses, one per supported driver.
 *
 * The control shell decides which cards and panels to show entirely from
 * `MouseStatus`, so a fixture that matches what a driver really reports
 * exercises the same rendering path the device would. That makes it possible to
 * check a shell change against every brand without owning every mouse.
 *
 * Each fixture is modelled on the corresponding driver's readStatus return, so
 * when a driver changes what it reports its fixture should change with it.
 */
export interface PreviewFixture {
  /** Shown in the picker and the live-status line. */
  label: string;
  status: MouseStatus;
}

const PULSAR: MouseStatus = {
  brand: "Pulsar",
  name: "Pulsar X2 V2",
  ui: { family: "pulsar", hideUnsupportedPollingRates: true },
  batteryPercent: 64,
  batteryState: "Discharging",
  dpi: 1600,
  pollingRateHz: 1000,
  supportedPollingRates: [125, 250, 500, 1000],
  activeProfile: 1,
  liftOffDistance: "Medium",
  connectionType: "Wireless",
  connectionDetail: "2.4 GHz receiver",
  dongleLedEnabled: true,
  signalStrength: 82,
  motionSync: true,
  debounceMs: 4,
  sleepTimeout: 30,
  angleSnapping: false,
  rippleControl: false,
  firmware: ["1.04.11"],
};

const PULSAR_PRO: MouseStatus = {
  ...PULSAR,
  name: "Pulsar X2 V2 Pro",
  performanceMode: true,
  angleTuning: 0,
  wheelAcceleration: false,
  pollingRateHz: 4000,
  supportedPollingRates: [125, 250, 500, 1000, 2000, 4000, 8000],
  firmware: ["2.01.03"],
};

const EGG_OP1: MouseStatus = {
  brand: "Endgame Gear",
  name: "OP1 8K",
  ui: { family: "egg-op1", hideLodLow: true, hideUnsupportedPollingRates: true },
  batteryPercent: null,
  batteryState: "Unknown",
  dpi: 3200,
  pollingRateHz: 8000,
  supportedPollingRates: [1000, 2000, 4000, 8000],
  activeProfile: 2,
  liftOffDistance: "Medium",
  connectionType: "Wired",
  motionSync: false,
  angleSnapping: false,
  rippleControl: false,
  leftSpdtMode: "GX Speed",
  rightSpdtMode: "GX Safe",
  eggCpiLevels: 4,
  eggCpiStages: [{ x: 800, y: 800 }, { x: 1600, y: 1600 }, { x: 3200, y: 3200 }, { x: 6400, y: 6400 }],
  eggPollingDivider: 1,
  eggMulticlickFilters: [0, 0],
  eggButtonMappings: ["Left", "Right", "Middle", "Back", "Forward"],
  firmware: ["1.02.00"],
};

const EGG_WE: MouseStatus = {
  brand: "Endgame Gear",
  name: "OP1we",
  ui: {
    family: "egg-we",
    settingsReady: true,
    hideLodLow: true,
    hideUnsupportedPollingRates: true,
    hideProcessingCard: true,
    forceShowBattery: true,
    pollingNote: "OP1we supports up to 1,000 Hz (125 / 250 / 500 / 1000).",
    defaultDisplayName: "Endgame Gear OP1we",
  },
  batteryPercent: 58,
  batteryState: "Discharging",
  dpi: 1600,
  pollingRateHz: 1000,
  supportedPollingRates: [125, 250, 500, 1000],
  activeProfile: 1,
  liftOffDistance: "Medium",
  connectionType: "Wireless",
  slamclickFilter: true,
  motionJitterFilter: false,
  firmware: ["1.00.07"],
};

const EGG_XM2WE: MouseStatus = {
  brand: "Endgame Gear",
  name: "XM2we",
  ui: {
    family: "egg-we",
    settingsReady: true,
    hideLodLow: true,
    hideUnsupportedPollingRates: true,
    hideProcessingCard: true,
    forceShowBattery: true,
    pollingNote: "Endgame Gear XM2we supports up to 1,000 Hz (125 / 250 / 500 / 1000).",
    defaultDisplayName: "Endgame Gear XM2we",
  },
  batteryPercent: 82,
  batteryState: "Discharging",
  dpi: 1600,
  pollingRateHz: 1000,
  supportedPollingRates: [125, 250, 500, 1000],
  activeProfile: 1,
  liftOffDistance: "Medium",
  connectionType: "Wireless",
  debounceMs: 4,
  sleepTimeout: 60,
  slamclickFilter: true,
  motionJitterFilter: false,
  firmware: ["1.00.07"],
};

const WLMOUSE: MouseStatus = {
  brand: "WLMouse",
  name: "BEAST X",
  ui: {
    family: "wlmouse",
    hideUnsupportedPollingRates: true,
    forceShowBattery: true,
    dpiStageEditor: { maxStages: 6, countEditable: true, minDpi: 50, maxDpi: 30000, stepDpi: 50 },
  },
  batteryPercent: 91,
  batteryState: "Charging",
  dpi: 800,
  dpiY: 800,
  dpiStages: [400, 800, 1600, 3200],
  activeDpiStage: 1,
  supportsSeparateDpiAxes: true,
  pollingRateHz: 8000,
  supportedPollingRates: [125, 250, 500, 1000, 2000, 4000, 8000],
  activeProfile: 1,
  liftOffDistance: "Low",
  connectionType: "Wireless",
  motionSync: true,
  hyperMode: true,
  turboMode: false,
  buttonCombination: true,
  angleTuning: -8,
  debounceMs: 2,
  sleepTimeout: 60,
  firmware: ["0.9.2"],
};

const LAMZU: MouseStatus = {
  brand: "Lamzu",
  name: "Atlantis OG V2",
  ui: { family: "lamzu", hideUnsupportedPollingRates: true, forceShowBattery: true },
  batteryPercent: 47,
  batteryState: "Discharging",
  dpi: 1600,
  dpiY: 1600,
  supportsSeparateDpiAxes: true,
  pollingRateHz: 4000,
  supportedPollingRates: [125, 250, 500, 1000, 2000, 4000],
  activeProfile: 3,
  liftOffDistance: "Medium",
  connectionType: "Wireless",
  motionSync: false,
  debounceMs: 3,
  sleepTimeout: 30,
  firmware: ["1.1.4"],
};

const CRDRAKO: MouseStatus = {
  brand: "CRDRAKO",
  name: "CRDRAKO KO-ONE",
  ui: { family: "crdrako", hideUnsupportedPollingRates: true, forceShowBattery: true },
  batteryPercent: 68,
  batteryState: "Discharging",
  dpi: 1600,
  dpiY: 1600,
  supportsSeparateDpiAxes: true,
  pollingRateHz: 8000,
  supportedPollingRates: [125, 250, 500, 1000, 2000, 4000, 8000],
  activeProfile: 1,
  liftOffDistance: "Low",
  connectionType: "Wireless",
  connectionDetail: "2.4 GHz receiver",
  motionSync: true,
  angleSnapping: false,
  rippleControl: false,
  performanceMode: true,
  hyperMode: true,
  debounceMs: 2,
  sleepTimeout: 60,
  firmware: ["Mouse 1.0.3", "Dongle 1.0.2"],
};

const ATTACKSHARK: MouseStatus = {
  brand: "Attack Shark" as MouseStatus["brand"],
  name: "Attack Shark R5 Ultra",
  ui: { family: "attack-shark", hideUnsupportedPollingRates: true, forceShowBattery: true },
  batteryPercent: 82,
  batteryState: "Discharging",
  dpi: 1600,
  dpiY: 1600,
  supportsSeparateDpiAxes: true,
  pollingRateHz: 8000,
  supportedPollingRates: [500, 1000, 2000, 4000, 8000],
  activeProfile: 1,
  liftOffDistance: "Medium",
  connectionType: "Wireless",
  connectionDetail: "2.4 GHz receiver",
  motionSync: true,
  angleSnapping: false,
  rippleControl: false,
  debounceMs: 3,
  sleepTimeout: 60,
  firmware: ["Mouse 1.0.4", "Dongle 1.0.3"],
};

const M3K: MouseStatus = {
  // The Zaunkoenig driver is being prepared in mouse-protocol. This assertion
  // can disappear when the website refreshes to that package revision.
  brand: "Zaunkoenig" as MouseStatus["brand"],
  name: "Zaunkoenig M3K",
  ui: {
    family: "zaunkoenig",
    hideUnsupportedPollingRates: true,
    hideMotionSync: true,
    hideRippleControl: true,
    hideSleepCard: true,
    hideSignalCard: true,
    showAdvancedSection: true,
    pollingNote: "Full-speed is limited to 1,000 Hz; High-speed supports 1,000–8,000 Hz.",
    defaultDisplayName: "Zaunkoenig M3K",
  },
  batteryPercent: null,
  batteryState: "Unknown",
  dpi: 800,
  pollingRateHz: 8000,
  supportedPollingRates: [1000, 2000, 4000, 8000],
  activeProfile: null,
  liftOffDistance: "Medium",
  supportedLiftOffDistances: ["Low", "Medium", "High"],
  connectionType: "Wired",
  connectionDetail: "USB High-speed",
  angleSnapping: false,
  motionSync: null,
  rippleControl: null,
  firmware: ["parawizard new v0.8.2"],
};

const ATK: MouseStatus = {
  brand: "ATK",
  name: "A9 Ultra",
  ui: { family: "atk", hideUnsupportedPollingRates: true, forceShowBattery: true },
  batteryPercent: 73,
  batteryState: "Unknown",
  dpi: 1600,
  dpiY: 1600,
  supportsSeparateDpiAxes: false,
  pollingRateHz: 8000,
  supportedPollingRates: [125, 250, 500, 1000, 2000, 4000, 8000],
  activeProfile: null,
  liftOffDistance: "Medium",
  connectionType: "Wireless",
  firmware: ["1.0.0"],
};

const ORBITAL: MouseStatus = {
  brand: "Orbital",
  name: "Orbital One",
  ui: { defaultDisplayName: "Orbital One", hideLodLow: false, hideUnsupportedPollingRates: true },
  batteryPercent: 88,
  batteryState: "Discharging",
  dpi: 1600,
  dpiY: 1600,
  supportsSeparateDpiAxes: true,
  pollingRateHz: 2000,
  supportedPollingRates: [125, 250, 500, 1000, 2000, 4000],
  activeProfile: 1,
  liftOffDistance: "Low",
  connectionType: "Wireless",
  motionSync: true,
  debounceMs: 5,
  sleepTimeout: 180,
  firmware: ["1.3.0"],
};

const RAZER: MouseStatus = {
  brand: "Razer",
  name: "Viper V3 Pro",
  ui: {
    family: "razer",
    settingsReady: true,
    valuesVerified: true,
    hideUnsupportedPollingRates: true,
    hideProcessingCard: true,
    forceShowBattery: true,
    defaultDisplayName: "Viper V3 Pro",
  },
  batteryPercent: 66,
  batteryState: "Discharging",
  dpi: 1600,
  dpiY: 1600,
  supportsSeparateDpiAxes: true,
  pollingRateHz: 1000,
  supportedPollingRates: [125, 250, 500, 1000, 2000, 4000, 8000],
  activeProfile: 1,
  liftOffDistance: null,
  supportedLiftOffDistances: [],
  connectionType: "Wireless",
  connectionDetail: "HyperSpeed receiver",
  razerButtonMappings: {
    leftClick: "Left Click",
    rightClick: "Right Click",
    mouse4: "Disabled",
    mouse5: "Mouse Button 5",
    scrollUp: "Scroll Up",
    scrollDown: "Disabled",
    sensitivityButton: "Cycle Up Sensitivity Stages",
  },
  firmware: ["1.01.00"],
};

/** Wireless Viper V2 Pro: Focus Pro 30K, stock receiver (1 kHz), asymmetric LOD. */
const RAZER_VIPER_V2: MouseStatus = {
  brand: "Razer",
  name: "Viper V2 Pro",
  ui: {
    family: "razer",
    settingsReady: true,
    valuesVerified: true,
    hideUnsupportedPollingRates: true,
    hideProcessingCard: true,
    hideSignalCard: true,
    showAdvancedSection: true,
    forceShowBattery: true,
    defaultDisplayName: "Viper V2 Pro",
  },
  batteryPercent: 71,
  batteryState: "Discharging",
  dpi: 1600,
  dpiY: 1600,
  supportsSeparateDpiAxes: true,
  pollingRateHz: 1000,
  supportedPollingRates: [125, 500, 1000],
  activeProfile: null,
  liftOffDistance: "Medium",
  supportedLiftOffDistances: ["Low", "Medium", "High"],
  asymmetricLiftOff: {
    enabled: true,
    liftOff: 10,
    landing: 5,
    liftOffRange: { min: 2, max: 26 },
    landingRange: { min: 1, max: 25 },
  },
  sleepTimeout: 180,
  lowBatteryWarning: 15,
  connectionType: "Wireless",
  connectionDetail: "HyperSpeed receiver",
  firmware: ["Mouse 1.00.00"],
};

const RAZER_VIPER_V4: MouseStatus = {
  ...RAZER,
  name: "Viper V4 Pro",
  ui: { family: "razer-viper-v4-pro", hideUnsupportedPollingRates: true, hideProcessingCard: true, forceShowBattery: true },
  pollingRateHz: 8000,
  sleepTimeout: 300,
  lowBatteryWarning: 15,
  firmware: ["1.00.04"],
};

const RAZER_VIPER_MINI_LIGHTING: MouseLighting = {
  zone: "Logo",
  modes: ["Off", "Spectrum", "Static", "Reactive", "Breathing random", "Breathing single", "Breathing dual"],
  mode: "Breathing dual",
  color: "#00ff00",
  color2: "#ff0000",
  colorModes: ["Static", "Reactive", "Breathing single", "Breathing dual"],
  dualColorModes: ["Breathing dual"],
  reactiveModes: ["Reactive"],
  speeds: [1, 2, 3, 4],
  speed: 2,
  writeOnly: true,
};

const RAZER_VIPER_MINI: MouseStatus = {
  brand: "Razer",
  name: "Viper Mini",
  ui: {
    family: "razer",
    settingsReady: true,
    valuesVerified: true,
    hideUnsupportedPollingRates: true,
    hideProcessingCard: true,
    defaultDisplayName: "Viper Mini",
  },
  batteryPercent: null,
  batteryState: "Unknown",
  dpi: 800,
  dpiY: 800,
  supportsSeparateDpiAxes: true,
  pollingRateHz: 1000,
  supportedPollingRates: [125, 500, 1000],
  activeProfile: null,
  liftOffDistance: null,
  supportedLiftOffDistances: [],
  connectionType: "Wired",
  connectionDetail: "Wired USB",
  lighting: RAZER_VIPER_MINI_LIGHTING,
  firmware: ["Mouse 1.01"],
};

const RAZER_COBRA: MouseStatus = {
  ...RAZER_VIPER_MINI,
  name: "Cobra",
  dpi: 1600,
  dpiY: 1600,
  ui: {
    family: "razer",
    settingsReady: true,
    valuesVerified: true,
    hideUnsupportedPollingRates: true,
    hideProcessingCard: true,
    defaultDisplayName: "Cobra",
  },
  firmware: ["Mouse 1.00"],
};

const TEEVOLUTION: MouseStatus = {
  brand: "Teevolution",
  name: "Terra Pro",
  ui: {
    defaultDisplayName: "Terra Pro",
    hideUnsupportedPollingRates: true,
    hideSignalCard: true,
    dpiStageEditor: {
      maxStages: 4,
      countEditable: true,
      minDpi: 50,
      maxDpi: 42000,
      stepDpi: 50,
    },
  },
  batteryPercent: 52,
  batteryState: "Discharging",
  dpi: 1600,
  dpiStages: [400, 800, 1600, 3200],
  activeDpiStage: 2,
  pollingRateHz: 1000,
  supportedPollingRates: [125, 250, 500, 1000],
  activeProfile: 1,
  liftOffDistance: "Medium",
  connectionType: "Wireless",
  connectionDetail: "CID 1 · MID 2 · Type 3",
  sensorMode: "Eco",
  sensorModeStored: 0,
  sensorModeEditable: true,
  performanceMode: false,
  performanceDuration: 6,
  dpiLedMode: 1,
  dpiLedBrightness: 5,
  dpiLedSpeed: 3,
  motionSync: false,
  debounceMs: 4,
  sleepTimeout: 60,
  firmware: ["1.0.2"],
};

const VGN: MouseStatus = {
  brand: "VGN",
  name: "F2 Master Plus",
  ui: { family: "vgn", hideUnsupportedPollingRates: true, forceShowBattery: true },
  batteryPercent: 79,
  batteryState: "Discharging",
  dpi: 1600,
  pollingRateHz: 4000,
  supportedPollingRates: [125, 250, 500, 1000, 2000, 4000],
  activeProfile: 1,
  liftOffDistance: "Medium",
  connectionType: "Wireless",
  motionSync: true,
  debounceMs: 4,
  sleepTimeout: 60,
  firmware: ["1.2.0"],
};

const FINALMOUSE: MouseStatus = {
  brand: "Finalmouse",
  name: "Finalmouse UltralightX",
  ui: {
    family: "finalmouse-ulx",
    defaultDisplayName: "Finalmouse UltralightX",
    hideUnsupportedPollingRates: true,
    forceShowBattery: true,
  },
  batteryPercent: 76,
  batteryVoltageMv: 3890,
  batteryState: "Discharging",
  dpi: 1600,
  pollingRateHz: 8000,
  supportedPollingRates: [125, 500, 1000],
  activeProfile: null,
  connectionType: "Wireless",
  connectionDetail: "2.4 GHz receiver · -48 dBm",
  motionSync: true,
  liftOffDistance: "Medium",
  supportedLiftOffDistances: ["Medium", "High"],
  finalmouseDongleLedMode: 1,
  finalmouseTournamentScrollMode: 3,
  finalmouseTournamentScrollTimeoutMs: 500,
  firmware: ["Mouse 1.0.7", "Dongle RF 1.0.4", "Dongle USB 1.0.3"],
};

const NINJUTSO: MouseStatus = {
  brand: "Ninjutso",
  name: "Ninjutso Sora V3",
  ui: {
    family: "ninjutso",
    hideUnsupportedPollingRates: true,
    hideSignalCard: true,
    hideMotionSync: true,
    hideAngleSnapping: true,
    hideRippleControl: true,
    showAdvancedSection: true,
    forceShowBattery: true,
    pollingNote: "NinjaForce exposes 1,000–8,000 Hz on this protocol.",
  },
  batteryPercent: 73,
  batteryState: "Discharging",
  dpi: 800,
  pollingRateHz: 1000,
  supportedPollingRates: [1000, 2000, 4000, 8000],
  activeProfile: 1,
  connectionType: "Wireless",
  connectionDetail: "2.4 GHz receiver · NinjaForce protocol",
  motionSync: null,
  angleSnapping: null,
  rippleControl: null,
  liftOffDistance: "Medium",
  supportedLiftOffDistances: ["Low", "Medium", "High"],
  sleepTimeout: 180,
  ninjutsoSystemMode: "Competitive",
  ninjutsoSystemModes: ["High Speed", "Competitive", "Ultra"],
  ninjutsoHyperClick: true,
  ninjutsoOpticalEngine: "Standard",
  ninjutsoSlamClick: "Medium",
  lighting: {
    zone: "Receiver",
    modes: ["Off", "Static", "Wave"],
    mode: "Wave",
    color: "#ff0099",
    color2: null,
    colorModes: ["Static"],
    dualColorModes: [],
    reactiveModes: ["Wave"],
    speeds: Array.from({ length: 21 }, (_, index) => index),
    speed: 12,
    brightness: 50,
    brightnessLevels: [25, 50, 75, 100],
  },
  firmware: ["Mouse 1611", "Receiver 0116"],
};

const KEYCHRON: MouseStatus = {
  brand: "Keychron",
  name: "Nape Pro",
  ui: {
    family: "keychron-nape",
    defaultDisplayName: "Nape Pro",
    hideUnsupportedPollingRates: true,
    hideProcessingCard: true,
    forceShowBattery: true,
    showAdvancedSection: true,
    pollingNote: "Nape Pro exposes polling through Keychron's misc HID commands when the firmware allows it.",
    dpiStageEditor: {
      maxStages: 5,
      countEditable: false,
      minDpi: 50,
      maxDpi: 4000,
      stepDpi: 50,
    },
  },
  batteryPercent: 76,
  batteryState: "Discharging",
  dpi: 800,
  dpiStages: [400, 800, 1600, 2400, 4000],
  activeDpiStage: 1,
  pollingRateHz: 1000,
  supportedPollingRates: [500, 1000, 2000, 4000, 8000],
  activeProfile: null,
  connectionType: "Wired",
  connectionDetail: "Wired USB · 90° orientation · DPI stage 2/5 · Layer 0",
  liftOffDistance: null,
  supportedLiftOffDistances: [],
  sleepTimeout: 600,
  napeLayer: 1,
  napeLayerCount: 8,
  firmware: ["v1.0.4"],
};

const LOGITECH_LEGACY: MouseStatus = {
  brand: "Logitech",
  name: "G402 Hyperion Fury",
  ui: { family: "logitech-hidpp", lodRequiresSurface: true },
  batteryPercent: null,
  batteryState: "Unknown",
  dpi: 1200,
  pollingRateHz: 1000,
  supportedPollingRates: [125, 250, 500, 1000],
  activeProfile: 1,
  // Legacy 0x2201 exposes no lift-off, which must hide the sensor card.
  liftOffDistance: null,
  supportedLiftOffDistances: [],
  connectionType: "Wired",
  connectionDetail: "Wired USB",
  firmware: ["MPM 12.01"],
};

const LOGITECH_G703_ZONE = (zone: string, color: string): MouseLighting => ({
  zone,
  modes: ["Off", "Static", "Cycling", "Wave", "Breathing single"],
  mode: "Static",
  color,
  color2: null,
  colorModes: ["Static", "Breathing single"],
  dualColorModes: [],
  reactiveModes: ["Cycling", "Wave", "Breathing single"],
  speeds: [1000, 2000, 3000, 5000, 10000],
  speed: 5000,
  writeOnly: true,
});

/** Wired G703 capture: legacy DPI, format-3 HEAT, Primary/Logo write-only RGB. */
const LOGITECH_G703: MouseStatus = {
  brand: "Logitech",
  name: "G703",
  ui: {
    family: "logitech-hidpp",
    lodRequiresSurface: true,
    hideUnsupportedPollingRates: true,
    defaultDisplayName: "G703",
  },
  batteryPercent: 78,
  batteryState: "Charging",
  dpi: 450,
  pollingRateHz: 1000,
  supportedPollingRates: [125, 250, 500, 1000],
  activeProfile: 3,
  deviceMode: "Onboard",
  liftOffDistance: null,
  supportedLiftOffDistances: [],
  connectionType: "Wired",
  connectionDetail: "Wired USB",
  transportIds: { USB: "C087" },
  onboardProfileFormat: {
    id: 3,
    name: "HEAT",
    base: "v1",
    supported: true,
    verified: true,
    writable: true,
  },
  lighting: LOGITECH_G703_ZONE("Primary", "#7c5cff"),
  lightingZones: [
    LOGITECH_G703_ZONE("Primary", "#7c5cff"),
    LOGITECH_G703_ZONE("Logo", "#35d59a"),
  ],
  firmware: ["MPM 14.02", "BOT 64.00", "RQI 04.00"],
};

/** Logi Bolt productivity mouse: DPI + battery, no report-rate or LOD feature. */
const LOGITECH_MX_MASTER_3S: MouseStatus = {
  brand: "Logitech",
  name: "MX Master 3S",
  ui: {
    family: "logitech-hidpp",
    lodRequiresSurface: true,
    hideUnsupportedPollingRates: true,
    pollingReadOnly: true,
    pollingNote: "This mouse does not expose a HID++ polling-rate control.",
  },
  batteryPercent: 68,
  batteryState: "Discharging",
  dpi: 1000,
  pollingRateHz: 0,
  supportedPollingRates: [],
  activeProfile: null,
  liftOffDistance: null,
  supportedLiftOffDistances: [],
  connectionType: "Wireless",
  connectionDetail: "Logi Bolt",
  firmware: ["RQK 70.00"],
};

/**
 * Keyed by the `?preview=` value. `superstrike` and `slots` are handled
 * separately because they drive panels beyond a plain status.
 */
export const PREVIEW_FIXTURES: Record<FixturePreviewMode, PreviewFixture> = {
  pulsar: { label: "Pulsar X2 V2", status: PULSAR },
  "pulsar-pro": { label: "Pulsar X2 V2 Pro", status: PULSAR_PRO },
  "egg-op1": { label: "Endgame Gear OP1 8K", status: EGG_OP1 },
  "egg-we": { label: "Endgame Gear OP1we", status: EGG_WE },
  "egg-xm2we": { label: "Endgame Gear XM2we", status: EGG_XM2WE },
  wlmouse: { label: "WLMouse BEAST X", status: WLMOUSE },
  lamzu: { label: "Lamzu Atlantis OG V2", status: LAMZU },
  "attack-shark": { label: "Attack Shark R5 Ultra", status: ATTACKSHARK },
  crdrako: { label: "CRDRAKO KO-ONE", status: CRDRAKO },
  m3k: { label: "Zaunkoenig M3K", status: M3K },
  atk: { label: "ATK A9 Ultra", status: ATK },
  orbital: { label: "Orbital One", status: ORBITAL },
  razer: { label: "Razer Viper V3 Pro", status: RAZER },
  "razer-viper-v2": { label: "Razer Viper V2 Pro", status: RAZER_VIPER_V2 },
  "razer-viper-mini": { label: "Razer Viper Mini", status: RAZER_VIPER_MINI },
  "razer-cobra": { label: "Razer Cobra", status: RAZER_COBRA },
  "razer-viper-v4": { label: "Razer Viper V4 Pro", status: RAZER_VIPER_V4 },
  "terra-pro": { label: "Teevolution Terra Pro", status: TEEVOLUTION },
  vgn: { label: "VGN F2 Master Plus", status: VGN },
  finalmouse: { label: "Finalmouse UltralightX", status: FINALMOUSE },
  ninjutso: { label: "Ninjutso Sora V3", status: NINJUTSO },
  "nape-pro": { label: "Keychron Nape Pro", status: KEYCHRON },
  "mx-master-3s": { label: "Logitech MX Master 3S", status: LOGITECH_MX_MASTER_3S },
  g703: { label: "Logitech G703", status: LOGITECH_G703 },
  "logitech-legacy": { label: "Logitech G402 (legacy DPI)", status: LOGITECH_LEGACY },
};
