// ── Supported Devices Data ────────────────────────────────────────────────
//
// Source of truth for statuses is the driver registry in `@openmouse/protocol`
// (`src/drivers/registry.ts`). Keep the statuses below in sync with it:
//
//   supported  — a driver in `@openmouse/protocol` covers the device (and, for
//                the ones with a `pids` field, those PIDs exist in the
//                protocol registry). Verified hardware reports are preferred.
//   pr         — a pull request that adds the driver is open.
//   quickwin   — the protocol is implemented; only a PID/config entry is
//                missing (a small addition to the existing driver).
//   likely     — a driver exists that probably covers the model, but the exact
//                PID/interface has not been confirmed on hardware.
//   driver     — no driver exists; the protocol is not implemented.
//   unknown    — nothing is known about the protocol.
//   bridge     — a driver exists but the device's settings channel is out of
//                WebHID reach; configuration requires the OpenMouse Bridge
//                desktop companion (native control).
//   pending    — a live community request from the support catalog. Not part
//                of the static table; `src/supported-live.ts` adds these at
//                runtime.
//
// `src/supported-mice.test.ts` re-checks every `supported`/`quickwin` claim and
// every PID against the protocol package so this table cannot silently drift
// from the code again. `src/supported-live.ts` additionally overlays live
// request counts and registry-listed supported models at runtime.

export type Status = "supported" | "pr" | "quickwin" | "likely" | "driver" | "unknown" | "bridge" | "pending";

export interface Mouse {
  brand: string;
  model: string;
  status: Status;
  /** Request votes. `pending` rows and matches against the live catalog are
   *  overlaid at runtime; otherwise this is the last-known baseline. */
  req: number;
  note: string;
  /** Known product IDs, where the protocol pins them (checked by tests). */
  pids?: readonly number[];
}

export const STATUS: Record<Status, { label: string; order: number }> = {
  supported: { label: "Supported",     order: 0 },
  pr:        { label: "PR pending",    order: 1 },
  quickwin:  { label: "Quick Win",     order: 2 },
  likely:    { label: "Test Needed",   order: 3 },
  driver:    { label: "Driver Needed", order: 4 },
  unknown:   { label: "Unknown",       order: 5 },
  bridge:    { label: "Needs Bridge",  order: 6 },
  pending:   { label: "Requested",     order: 7 },
};

export const TABS: Array<{ key: Status | "all"; label: string }> = [
  { key: "all",       label: "All" },
  { key: "supported", label: "Supported" },
  { key: "pr",        label: "PR pending" },
  { key: "quickwin",  label: "Quick Win" },
  { key: "likely",    label: "Test Needed" },
  { key: "driver",    label: "Driver Needed" },
  { key: "unknown",   label: "Unknown" },
  { key: "bridge",    label: "Needs Bridge" },
  { key: "pending",   label: "Requested" },
];

export const MICE: Mouse[] = [
  // LOGITECH ─────────────────────────────────────────────────────────────
  { brand: "Logitech", model: "G502 (all variants)",    status: "supported", req: 42,
    pids: [0xc07d, 0xc08b],
    note: "Wired PIDs 0xc07d (G502) / 0xc08b (HERO) in driver; Lightspeed dongle variants also work" },
  { brand: "Logitech", model: "G203 LIGHTSYNC",         status: "supported", req: 3,
    pids: [0xc092],
    note: "PID 0xc092 — HID++ direct, legacy DPI feature 0x2201" },
  { brand: "Logitech", model: "G203 PRODIGY",           status: "supported", req: 2,
    pids: [0xc084],
    note: "PID 0xc084 — HID++ direct, legacy DPI feature 0x2201" },
  { brand: "Logitech", model: "G102 LIGHTSYNC",         status: "supported", req: 1,
    pids: [0xc089],
    note: "PID 0xc089 — same family as G203, HID++ direct" },
  { brand: "Logitech", model: "G402 Hyperion Fury",     status: "supported", req: 3,
    pids: [0xc07e],
    note: "PID 0xc07e — HID++ direct, legacy DPI feature 0x2201" },
  { brand: "Logitech", model: "G303 Daedalus Apex",     status: "supported", req: 1,
    pids: [0xc080],
    note: "PID 0xc080 — HID++ direct" },
  { brand: "Logitech", model: "G Pro (2017)",           status: "supported", req: 2,
    pids: [0xc085],
    note: "PID 0xc085 — HID++ direct, DPI feature 0x2202" },
  { brand: "Logitech", model: "G502 HERO (wired)",      status: "supported", req: 3,
    pids: [0xc08b],
    note: "PID 0xc08b — HID++ direct, DPI feature 0x2202" },
  { brand: "Logitech", model: "G Pro Hero",             status: "supported", req: 2,
    pids: [0xc08c],
    note: "PID 0xc08c — HID++ direct" },
  { brand: "Logitech", model: "G903 HERO (wired)",      status: "supported", req: 2,
    pids: [0xc08e],
    note: "PID 0xc08e — HID++ direct" },
  { brand: "Logitech", model: "G403 HERO (wired)",      status: "supported", req: 1,
    pids: [0xc08f],
    note: "PID 0xc08f — HID++ direct, DPI feature 0x2202" },
  { brand: "Logitech", model: "G703 (wired)",           status: "supported", req: 1,
    note: "PID 0xc087 — HID++ direct, legacy DPI 0x2201, onboard format 3 (HEAT) writable" },
  { brand: "Logitech", model: "G Pro X Superlight",     status: "supported", req: 4,
    pids: [0xc094],
    note: "PID 0xc094 — HID++ direct" },
  { brand: "Logitech", model: "G305",                   status: "supported", req: 8,
    note: "Lightspeed receiver — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "MX Master 3S",           status: "supported", req: 8,
    pids: [0xc548],
    note: "Logi Bolt receiver (0xc548) already in driver" },
  { brand: "Logitech", model: "G502 X (wired)",         status: "supported", req: 31,
    pids: [0xc099],
    note: "PID 0xc099 — HID++ direct, in driver" },
  { brand: "Logitech", model: "G502 X PLUS (wireless)", status: "supported", req: 27,
    pids: [0xc095],
    note: "PID 0xc095 (USB) in driver; Lightspeed dongle also works" },
  { brand: "Logitech", model: "G502 X LIGHTSPEED",      status: "supported", req: 2,
    pids: [0xc098],
    note: "Lightspeed dongle — HID++ 2.0 protocol supported; PID 0xc098 (USB cable, direct-connect) also in driver" },
  { brand: "Logitech", model: "MX Vertical",            status: "driver",    req: 9,
    note: "Unifying (HID++ 1.0) / Bluetooth — not implemented" },
  { brand: "Logitech", model: "MX Master 4S",           status: "likely",    req: 8,
    note: "Logi Bolt receiver in driver — needs hardware test" },
  { brand: "Logitech", model: "G304",                   status: "supported", req: 7,
    note: "Lightspeed receiver — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "G Pro Wireless",         status: "supported", req: 6,
    note: "Lightspeed dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "G300s",                  status: "driver",    req: 4,
    note: "Older HID++ 1.0 protocol variant — not implemented" },
  { brand: "Logitech", model: "G600",                   status: "driver",    req: 4,
    note: "HID++ 1.0 protocol variant — not yet implemented" },
  { brand: "Logitech", model: "G Pro 2 Lightspeed",     status: "supported", req: 3,
    note: "Lightspeed dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "G502 Lightspeed",        status: "supported", req: 2,
    note: "Lightspeed USB dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "MX Master 2S",           status: "driver",    req: 2,
    note: "Unifying receiver (HID++ 1.0) — not implemented" },
  { brand: "Logitech", model: "MX Anywhere 3",          status: "supported", req: 2,
    pids: [0xc548],
    note: "Logi Bolt receiver (0xc548) in driver" },
  { brand: "Logitech", model: "G309 Lightspeed",        status: "supported", req: 1,
    note: "Lightspeed USB dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "MX Ergo S",              status: "supported", req: 1,
    pids: [0xc548],
    note: "Logi Bolt receiver (0xc548) in driver" },
  { brand: "Logitech", model: "MX Anywhere 2",          status: "driver",    req: 1,
    note: "Unifying receiver (HID++ 1.0) — not implemented" },
  { brand: "Logitech", model: "Compact Wireless",       status: "unknown",   req: 1,
    note: "Protocol unknown — receiver type needs identification" },
  { brand: "Logitech", model: "G700s",                  status: "driver",    req: 1,
    note: "HID++ 1.0 (legacy protocol) — not implemented" },
  { brand: "Logitech", model: "M171 Wireless",          status: "driver",    req: 1,
    note: "Basic optical — no HID++ control channel exposed" },

  // ROCCAT ─────────────────────────────────────────────────────────────
  { brand: "Roccat", model: "Kone Pro Air",             status: "driver",    req: 39,
    note: "Roccat Swarm / AIMO protocol — not implemented" },
  { brand: "Roccat", model: "Kone XP Air",              status: "driver",    req: 5,
    note: "Roccat AIMO protocol — not implemented" },
  { brand: "Roccat", model: "Tyon",                     status: "driver",    req: 2,
    note: "Roccat protocol — not implemented" },
  { brand: "Roccat", model: "Nyth",                     status: "driver",    req: 2,
    note: "Roccat protocol — not implemented" },
  { brand: "Roccat", model: "Kain 100 AIMO",            status: "driver",    req: 2,
    note: "Roccat AIMO protocol — not implemented" },
  { brand: "Roccat", model: "Kone Pro",                 status: "driver",    req: 1,
    note: "Roccat protocol — not implemented" },

  // REDRAGON ─────────────────────────────────────────────────────────────
  { brand: "Redragon", model: "M725 Honeycomb",         status: "driver",    req: 32,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "Impact Elite M913",      status: "driver",    req: 18,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "PREDATOR M612",          status: "driver",    req: 2,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "K1ng M916 Pro 4K",      status: "driver",    req: 2,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M711 Cobra",             status: "driver",    req: 2,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M917 Pro",               status: "driver",    req: 2,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M991",                   status: "driver",    req: 2,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M703",                   status: "driver",    req: 2,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "TAIPAN PRO M810",        status: "driver",    req: 2,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "Ranger Lite",            status: "driver",    req: 1,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "Infernal Dragon",        status: "driver",    req: 1,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M696 Pro",               status: "driver",    req: 1,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M721 Pro",               status: "driver",    req: 1,
    note: "Redragon HID protocol — not implemented" },

  // ATTACK SHARK ────────────────────────────────────────────────────────
  { brand: "Attack Shark", model: "X3",                 status: "bridge",    req: 15,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X11",                status: "bridge",    req: 10,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x1d57 / 0x25a7 families)" },
  { brand: "Attack Shark", model: "R5 Ultra",           status: "supported", req: 7,
    pids: [0x0046, 0x0047],
    note: "PIDs 0x0046/0x0047 in the CompX/Lamzu driver (R5 Ultra profile)" },
  { brand: "Attack Shark", model: "X6",                 status: "bridge",    req: 5,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "R3",                 status: "bridge",    req: 4,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x373e family)" },
  { brand: "Attack Shark", model: "R1",                 status: "bridge",    req: 3,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x1d57 family)" },
  { brand: "Attack Shark", model: "X8 Ultra",           status: "bridge",    req: 3,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X8 SE",              status: "bridge",    req: 2,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x1d57 VID, GearHub protocol)" },
  { brand: "Attack Shark", model: "X1",                 status: "bridge",    req: 2,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "V3 Pro",             status: "bridge",    req: 1,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X3 Pro",             status: "bridge",    req: 1,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X11 SE",             status: "bridge",    req: 1,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x1d57 / 0x25a7 families)" },
  { brand: "Attack Shark", model: "X8 PLUS",            status: "bridge",    req: 1,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X12",                status: "bridge",    req: 1,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 family)" },
  { brand: "Attack Shark", model: "R6",                 status: "bridge",    req: 1,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 family)" },
  { brand: "Attack Shark", model: "G3",                 status: "bridge",    req: 1,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 family)" },
  { brand: "Attack Shark", model: "R2",                 status: "bridge",    req: 1,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 family)" },

  // RAZER ───────────────────────────────────────────────────────────────
  { brand: "Razer", model: "DeathAdder V3 (wired)",     status: "supported", req: 9,
    note: "Confirmed working ✓" },
  { brand: "Razer", model: "DeathAdder V2 (wired)",     status: "supported", req: 3,
    pids: [0x0084],
    note: "PID 0x0084 — specific driver filter" },
  { brand: "Razer", model: "DeathAdder V2 Pro",         status: "supported", req: 3,
    pids: [0x007c, 0x007d],
    note: "PIDs 0x007c/0x007d in Razer registry" },
  { brand: "Razer", model: "Cobra",                     status: "supported", req: 2,
    pids: [0x00a3],
    note: "PID 0x00a3 — specific driver filter" },
  { brand: "Razer", model: "Viper V3 Pro",              status: "supported", req: 1,
    pids: [0x00c0, 0x00c1],
    note: "PIDs 0x00c0 / 0x00c1 — specific driver filter" },
  { brand: "Razer", model: "DeathAdder Essential",      status: "supported", req: 1,
    pids: [0x006e, 0x0071, 0x0098],
    note: "PIDs 0x006e / 0x0071 / 0x0098 — specific driver filters" },
  { brand: "Razer", model: "Viper Mini",                status: "supported", req: 3,
    pids: [0x008a],
    note: "PID 0x008a — dedicated Viper Mini driver" },
  { brand: "Razer", model: "Viper V3 HyperSpeed",       status: "supported", req: 1,
    pids: [0x00b8],
    note: "PID 0x00b8 — verified on hardware" },
  { brand: "Razer", model: "Viper V4 Pro",              status: "supported", req: 1,
    pids: [0x00e5, 0x00e6],
    note: "PIDs 0x00e5 (wired) / 0x00e6 (wireless) — dedicated driver, only mouse on Razer's own Synapse Web" },
  { brand: "Razer", model: "Basilisk V3 (wired)",       status: "likely",    req: 13,
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Basilisk V3 Pro",           status: "likely",    req: 13,
    note: "Wireless — in Razer registry, needs HyperSpeed dongle" },
  { brand: "Razer", model: "Viper Ultimate",            status: "likely",    req: 5,
    note: "Wired 0x007a works; wireless 0x007b is nativeOnly (Chrome won't expose control)" },
  { brand: "Razer", model: "Basilisk V3 X HyperSpeed",  status: "likely",    req: 5,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "DeathAdder V2 X HyperSpeed",status: "likely",    req: 1,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Viper 8KHz",                status: "likely",    req: 1,
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga V2 Pro",               status: "likely",    req: 3,
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "DeathAdder V3 Pro",         status: "likely",    req: 2,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "DeathAdder V4 Pro",         status: "supported", req: 2,
    pids: [0x00be, 0x00bf],
    note: "PIDs 0x00be (wired) / 0x00bf (wireless) — was nativeOnly until Razer's own live device list started reaching it over WebHID again" },
  { brand: "Razer", model: "DeathAdder V4 Pro Carbon Fiber Edition", status: "supported", req: 1,
    pids: [0x00ef, 0x00f0],
    note: "PIDs 0x00ef (wired) / 0x00f0 (wireless) — same driver as the standard edition, cosmetic SKU" },
  { brand: "Razer", model: "Naga Trinity",              status: "likely",    req: 2,
    note: "PID 0x0067 in Razer registry — standard transport" },
  { brand: "Razer", model: "Naga X",                    status: "likely",    req: 2,
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Basilisk Essential",        status: "likely",    req: 1,
    note: "In Razer device registry" },
  { brand: "Razer", model: "Basilisk V3 HyperSpeed",    status: "likely",    req: 1,
    note: "Wireless — in registry, needs dongle connected" },
  { brand: "Razer", model: "Basilisk",                  status: "likely",    req: 1,
    note: "In Razer device registry" },
  { brand: "Razer", model: "Orochi V2",                 status: "likely",    req: 1,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Cobra HyperSpeed",          status: "likely",    req: 1,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Viper V3 Pro SE",           status: "likely",    req: 1,
    pids: [0x00de, 0x00df],
    note: "PIDs 0x00de/0x00df now in Razer registry — needs hardware test" },
  { brand: "Razer", model: "Basilisk X HyperSpeed",     status: "likely",    req: 1,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Naga V2 HyperSpeed",        status: "likely",    req: 1,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Basilisk Ultimate",         status: "likely",    req: 1,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "DeathAdder Elite",          status: "likely",    req: 1,
    pids: [0x005c],
    note: "PID 0x005c in Razer registry — standard transport" },

  // HYPERX ─────────────────────────────────────────────────────────────
  { brand: "HyperX", model: "Pulsefire Haste 2",          status: "driver",  req: 10,
    note: "Kingston NGENUITY protocol — not implemented" },
  { brand: "HyperX", model: "Pulsefire Haste 2 Wireless", status: "driver",  req: 4,
    note: "Kingston NGENUITY protocol — not implemented" },
  { brand: "HyperX", model: "Pulsefire FPS Pro",          status: "driver",  req: 2,
    note: "Kingston NGENUITY protocol — not implemented" },
  { brand: "HyperX", model: "Pulsefire Fuse",             status: "driver",  req: 1,
    note: "Kingston NGENUITY protocol — not implemented" },

  // STEELSERIES ─────────────────────────────────────────────────────────
  { brand: "SteelSeries", model: "Aerox 9 Wireless",    status: "supported", req: 5,
    pids: [0x185a, 0x1876, 0x1858, 0x1874],
    note: "Write-only settings (DPI presets, polling, RGB zones/reactive/sleep-dim timers/rainbow/default lighting; no button-remap command in rivalcfg's profile for this device); battery percentage/charging is read live (no firmware-query command). PID 0x185a/0x1876 (wired mode) and 0x1858/0x1874 (2.4 GHz mode, WOW Edition) in SteelSeries Aerox 9 Wireless driver" },
  { brand: "SteelSeries", model: "Sensei Ten",           status: "supported", req: 4,
    pids: [0x1832, 0x1834],
    note: "Write-only: DPI presets (linear TrueMove3+-family encoding, not a lookup table), polling, logo/wheel LED RGB gradients, buttons; firmware version is read live. PID 0x1832 and 0x1834 (CS:GO Neon Rider Edition) in SteelSeries Sensei TEN driver" },
  { brand: "SteelSeries", model: "Aerox 5",              status: "supported", req: 2,
    pids: [0x1850, 0x1854, 0x185e, 0x1862, 0x1852, 0x185c, 0x1860],
    note: "Write-only settings (DPI presets, polling, RGB zones/reactive/brightness/rainbow, buttons); the Wireless variant's battery percentage/charging is read live. PID 0x1850 in SteelSeries Aerox 5 driver, 0x1854/0x185e/0x1862 (wired mode) and 0x1852/0x185c/0x1860 (2.4 GHz mode) in SteelSeries Aerox 5 Wireless driver" },
  { brand: "SteelSeries", model: "Rival 3 Wireless",     status: "supported", req: 2,
    pids: [0x1830],
    note: "DPI presets, polling, and buttons are write-only; battery percentage/charging and firmware are read live. PID 0x1830 (2.4 GHz mode) in SteelSeries Rival 3 Wireless driver" },
  { brand: "SteelSeries", model: "Rival 650 Wireless",   status: "supported", req: 2,
    pids: [0x172b, 0x1726],
    note: "DPI (preset 1), polling, lift-off distance, sleep timer, and buttons are write-only; battery percentage/charging is read live (no firmware-query command in this protocol). PID 0x172b (wired mode) and 0x1726 (2.4 GHz wireless mode) in SteelSeries Rival 650 Wireless driver" },
  { brand: "SteelSeries", model: "Aerox 3",              status: "supported", req: 1,
    pids: [0x1836],
    note: "Write-only: DPI presets, polling, RGB zones, reactive color, brightness, rainbow, buttons. PID 0x1836 in SteelSeries Aerox 3 driver" },
  { brand: "SteelSeries", model: "Prime+",               status: "supported", req: 1,
    pids: [0x182c],
    note: "Write-only: DPI presets, polling, wheel LED color, brightness, buttons. PID 0x182c in SteelSeries Prime+ driver" },
  { brand: "SteelSeries", model: "Rival 310",            status: "supported", req: 1,
    pids: [0x1720, 0x171e, 0x1736],
    note: "Write-only: DPI (preset 1), polling, logo/wheel LED steady color, buttons; firmware version is read live. PID 0x1720/0x171e (CS:GO Howl Edition)/0x1736 (PUBG Edition) in SteelSeries Rival 310 driver" },
  { brand: "SteelSeries", model: "Prime Mini Wireless",  status: "supported", req: 1,
    pids: [0x184a, 0x1848],
    note: "DPI presets, polling, LED color, sleep/dim timers, default lighting, and buttons are write-only; battery percentage/charging is read live (no firmware-query command in this protocol). PID 0x184a (wired mode) and 0x1848 (2.4 GHz mode) in SteelSeries Prime Mini Wireless driver" },

  // CORSAIR ─────────────────────────────────────────────────────────────
  { brand: "Corsair", model: "Harpoon RGB Pro",           status: "driver",   req: 5,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Katar Pro",                 status: "driver",   req: 4,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "M65 Pro RGB",               status: "driver",   req: 3,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Sabre V2 Pro Ultralight",   status: "driver",   req: 3,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Scimitar Elite Wireless SE",status: "driver",   req: 3,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "M65 RGB Elite",             status: "driver",   req: 1,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Scimitar RGB Elite",        status: "driver",   req: 1,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Ironclaw RGB",              status: "driver",   req: 1,
    note: "iCUE protocol — not implemented" },

  // GLORIOUS ────────────────────────────────────────────────────────────
  // Three tiers: the Pixart Model O 2 / I 2 family (write-only,
  // drivers/glorious/hid.ts); the pre-Pixart "core1" classic Model O/D/I
  // family (full DPI/polling/LOD/debounce/RGB write + read battery,
  // drivers/glorious/classic-hid.ts, ported from glorious-ctl + mxw); and the
  // newer 8000Hz-class "core2" devices on the SAME classic-hid.ts driver but
  // gated to RGB/debounce/battery only — DPI/polling/LOD stay off for core2
  // because korkje/mxw's own device list never included them, and (for
  // polling specifically) github.com/AMarcinkiewicz/GloriousAutoPollingRate
  // shows the D2 Pro 4K/8K's real polling command uses an entirely different
  // usage page/report layout, confirming core2 isn't just core1 with new
  // values. See [[glorious-classic-protocol]] in project memory for the full
  // writeup, including the exact (unwired) D2 Pro 4K/8K polling-rate bytes.
  { brand: "Glorious", model: "Model O 2 Pro Wireless",  status: "supported", req: 5,
    pids: [0x2033],
    note: "Same PID (0x2033) as the classic driver's \"Model O 2 Wireless\" — Glorious's own \"O2 Pro\" name for it, per AwesomeTy18/GloriousBatteryMonitor's device table. DPI/polling/LOD/debounce/RGB are write-only, battery is read" },
  { brand: "Glorious", model: "Model O",                 status: "supported", req: 3,
    pids: [0x2011, 0x2022],
    note: "Classic driver (VID 0x258a). DPI/polling/LOD/debounce/RGB are write-only, battery is read" },
  { brand: "Glorious", model: "Model D Wireless",        status: "supported", req: 2,
    pids: [0x2012, 0x2023],
    note: "Classic driver (VID 0x258a). DPI/polling/LOD/debounce/RGB are write-only, battery is read. Config collection may be usage 0xffff:0 on newer firmware — the classic driver accepts it" },
  { brand: "Glorious", model: "Model D",                 status: "supported",   req: 2,
    pids: [0x2012],
    note: "Same PID as Model D Wireless's wired mode — classic driver (VID 0x258a)" },
  { brand: "Glorious", model: "Model O2 Pro 4K/8K",     status: "likely",   req: 2,
    pids: [0x201b, 0x2035],
    note: "Classic driver recognizes this PID (VID 0x258a) but only writes RGB/debounce and reads battery — DPI/polling/LOD are unconfirmed on this newer \"core2\" firmware and stay off" },
  { brand: "Glorious", model: "Model O Pro",             status: "supported", req: 1,
    pids: [0x2015, 0x2027],
    note: "Classic driver (VID 0x258a) — full DPI/polling/LOD/debounce/RGB write, battery read, per RealCrystalNight/Glorious-Mouse-Toolkit-Linux's device table" },
  { brand: "Glorious", model: "Model D2 Pro Wireless 8K",status: "likely",  req: 1,
    pids: [0x201c, 0x2036],
    note: "Classic driver recognizes this PID (VID 0x258a) but only writes RGB/debounce and reads battery — DPI/polling/LOD are unconfirmed on this newer \"core2\" firmware and stay off" },
  { brand: "Glorious", model: "Model O3 Wireless",       status: "likely",   req: 5,
    pids: [0xa312, 0xa300],
    note: "8000Hz mouse on VID 0x3794. glorious-ctl's own device list includes it for RGB/debounce/battery, so the classic driver recognizes it for those — DPI/polling/LOD have no confirmed protocol and stay off" },

  // ENDGAME GEAR ────────────────────────────────────────────────────────
  { brand: "Endgame Gear", model: "XM2w 4K",            status: "supported", req: 3,
    note: "egg-we driver (0x3367) covers OP1we/XM2we family" },
  { brand: "Endgame Gear", model: "OP1we",            status: "supported", req: 1,
    pids: [0x1961, 0x1962],
    note: "egg-we driver (0x3367) covers OP1we/XM2we family" },
  { brand: "Endgame Gear", model: "OP1w 4K v2",         status: "likely",    req: 7,
    note: "egg-we driver (0x3367) covers OP1we/XM2we family — needs hardware test" },
  { brand: "Endgame Gear", model: "OP1 8K",             status: "supported", req: 1,
    pids: [0x1964, 0x1976, 0x1978],
    note: "Egg OP1 driver — PIDs 0x1964/0x1976/0x1978" },
  { brand: "Endgame Gear", model: "XM2 8K",             status: "supported", req: 1,
    pids: [0x1966, 0x1980],
    note: "Egg OP1 driver — PIDs 0x1966/0x1980" },

  // ATK / VGN ───────────────────────────────────────────────────────────
  { brand: "ATK", model: "F1 V2 Ultra Max",             status: "supported", req: 1,
    note: "ATK vendor (0x373b, usagePage 0xff02) covered" },
  { brand: "ATK", model: "VXE Dragonfly R1 Pro",        status: "likely",    req: 3,
    note: "VGN F2 driver (0xfb56/0xfb57) covers Dragonfly F2; R1 Pro needs test" },
  { brand: "VXE", model: "R1 SE+ (wired)",              status: "supported", req: 3,
    pids: [0xf58f],
    note: "Wired 0x3554:0xf58f identity, settings, profiles, and button inspection verified through Chromium WebHID. Wireless identity and receiver telemetry verified through the 0x3554:0xf58e 1K receiver" },
  { brand: "ATK", model: "X1 V2 Ultimate",              status: "likely",    req: 1,
    note: "ATK driver (0x373b) likely covers — needs hardware test" },
  { brand: "ATK", model: "A9 Air",                      status: "likely",    req: 1,
    note: "ATK driver (0x373b) likely covers — needs hardware test" },
  { brand: "ATK", model: "F1 Ultimate",                 status: "likely",    req: 1,
    note: "ATK driver (0x373b) likely covers — needs hardware test" },
  { brand: "ATK", model: "VXE Mad R Major",             status: "likely",    req: 1,
    note: "ATK driver (0x373b) likely covers — needs hardware test" },
  { brand: "ATK", model: "VXE Zero Normal",             status: "likely",    req: 1,
    note: "ATK driver (0x373b) likely covers — needs hardware test" },
  { brand: "VGN", model: "Dragonfly F2 Master+",        status: "supported", req: 1,
    pids: [0xfb56, 0xfb57],
    note: "VGN F2 driver — PIDs 0xfb56/0xfb57" },

  // WLMouse ─────────────────────────────────────────────────────────────
  { brand: "WLMouse", model: "Beast X",                 status: "supported", req: 1,
    pids: [0xa883, 0xa884],
    note: "PIDs 0xa883 / 0xa884 already in WLMouse driver" },
  { brand: "WLMouse", model: "Beast Mini",              status: "supported", req: 1,
    pids: [0xa885, 0xa886],
    note: "PIDs 0xa885 / 0xa886 in WLMouse driver" },
  { brand: "WLMouse", model: "Beast X Pro",             status: "supported", req: 1,
    pids: [0xa870, 0xa871],
    note: "PIDs 0xa870 / 0xa871 in WLMouse driver" },
  { brand: "WLMouse", model: "Sword X",                 status: "supported", req: 1,
    pids: [0xa878, 0xa879],
    note: "PIDs 0xa878 / 0xa879 in WLMouse driver" },
  { brand: "WLMouse", model: "Beast Max",               status: "supported", req: 1,
    pids: [0xa880, 0xa881],
    note: "PIDs 0xa880 / 0xa881 in WLMouse driver" },

  // PULSAR ──────────────────────────────────────────────────────────────
  { brand: "Pulsar", model: "Tenz Signature",           status: "supported", req: 6,
    note: "Pulsar driver (VID 0x3710) — collection-based detection" },
  { brand: "Pulsar", model: "X2h",                      status: "supported", req: 3,
    note: "Pulsar driver (VID 0x3710) — collection-based detection" },
  { brand: "Pulsar", model: "X2 V3 ES Mini",            status: "supported", req: 2,
    note: "Pulsar driver (VID 0x3710) — collection-based detection" },
  { brand: "Pulsar", model: "X3 Medium",                status: "supported", req: 1,
    pids: [0x3409, 0x3410, 0x5402, 0x5403],
    note: "XS-1 feature-report driver (usage 0xffff:1) — PIDs pinned in the protocol registry" },
  { brand: "Pulsar", model: "X2F",                      status: "supported", req: 1,
    note: "Pulsar driver (VID 0x3710) — collection-based detection" },

  // LAMZU / CRDRAKO ─────────────────────────────────────────────────────
  { brand: "Lamzu", model: "Maya X",                    status: "supported", req: 1,
    pids: [0x001c, 0x001d, 0x001e],
    note: "PIDs 0x001c/0x001d/0x001e in Lamzu driver" },
  { brand: "Lamzu", model: "Inca",                      status: "quickwin",  req: 1,
    note: "CompX protocol implemented; Inca PID not yet in driver" },
  { brand: "Lamzu", model: "Thorn",                     status: "quickwin",  req: 1,
    note: "CompX protocol implemented; Thorn PID not yet in driver" },
  { brand: "CRDRAKO", model: "KO-ONE",                  status: "supported", req: 1,
    pids: [0x006a, 0x006b],
    note: "PIDs 0x006a/0x006b in Lamzu/CompX driver" },

  // NINJUTSO ────────────────────────────────────────────────────────────
  { brand: "Ninjutso", model: "Sora V2",                status: "supported", req: 1,
    pids: [0xae11, 0xae12, 0xae13, 0xae14, 0xae15, 0xae16],
    note: "Legacy 0x1915 PIDs in Ninjutso driver" },
  { brand: "Ninjutso", model: "Sora V3",                status: "supported", req: 1,
    pids: [0xe010],
    note: "PID 0xe010 in Ninjutso driver" },
  { brand: "Ninjutso", model: "TEN",                    status: "supported", req: 1,
    pids: [0xe020, 0xea01],
    note: "PIDs 0xe020/0xea01 in Ninjutso driver" },
  { brand: "Ninjutso", model: "Sora",                   status: "likely",    req: 1,
    note: "Driver covers Sora V2/V3; original Sora PID not listed — needs test" },

  // TEEVOLUTION ─────────────────────────────────────────────────────────
  { brand: "Teevolution", model: "Terra Pro",           status: "supported", req: 1,
    pids: [0xf520, 0xf523, 0xf5bb, 0xf522],
    note: "PIDs 0xf520/0xf523/0xf5bb/0xf522 in Teevolution driver" },

  // WALLHACK ─────────────────────────────────────
  { brand: "WALLHACK", model: "M-001",                  status: "supported", req: 1,
    pids: [0x1110, 0x0807],
    note: "Full read/write: DPI, polling, LOD, processing, battery. PIDs 0x1110 (0x0807 demo) in WALLHACK mouse driver" },

  // FINALMOUSE ──────────────────────────────────────────────────────────
  { brand: "Finalmouse", model: "Starlight-12 / ULX",   status: "supported", req: 1,
    pids: [0x0100],
    note: "ULX dongle PID 0x0100 in Finalmouse driver" },

  // ZAUNKOENIG ──────────────────────────────────────────────────────────
  { brand: "Zaunkoenig", model: "M3K",                  status: "supported", req: 1,
    pids: [0xa462],
    note: "PID 0xa462 in Zaunkoenig driver" },
  { brand: "Zaunkoenig", model: "M2K",                  status: "supported", req: 1,
    pids: [0xa3cf],
    note: "PID 0xa3cf in Zaunkoenig driver" },

  // MODDO / ORBITAL ─────────────────────────────────────────────────────
  { brand: "moddoMOUSE", model: "moddoMOUSE",           status: "supported", req: 1,
    note: "Vendor config interface (0x2fe3) in moddo driver" },
  { brand: "Orbital", model: "Ghost / Pathfinder V2",   status: "supported", req: 1,
    pids: [0x080c],
    note: "PID 0x080c in Orbital driver" },

  // KEYCHRON ────────────────────────────────────────────────────────────
  { brand: "Keychron", model: "Nape Pro",               status: "supported", req: 1,
    pids: [0x0440],
    note: "PID 0x0440 in Keychron driver" },
  { brand: "Keychron", model: "M6",                     status: "quickwin",  req: 1,
    note: "Nape VIA driver only; M6 uses a different Keychron mouse protocol" },

  // Asus ────────────────────────────────────────────────────────────────
  { brand: "Asus",     model: "Harpe Ace Aim Lab",      status: "driver",    req: 5,
    note: "Armoury Crate protocol — not implemented" },
  { brand: "Asus",     model: "TUF Gaming M5",          status: "driver",    req: 2,
    note: "Armoury Crate protocol — not implemented" },
  { brand: "Asus",     model: "Gladius II Core",        status: "driver",    req: 1,
    note: "Armoury Crate protocol — not implemented" },
  { brand: "Asus",     model: "Strix Impact III",       status: "driver",    req: 1,
    note: "Armoury Crate protocol — not implemented" },
  { brand: "Asus",     model: "TUF Gaming M3 Gen 1",    status: "driver",    req: 1,
    note: "Armoury Crate protocol — not implemented" },

  // OTHER DRIVER-NEEDED ─────────────────────────────────────────────────
  { brand: "Bloody",        model: "Max W95",           status: "driver",    req: 1,
    note: "A4tech / Bloody protocol — not implemented" },
  { brand: "Fantech",       model: "THOR II X16",       status: "driver",    req: 1,
    note: "Fantech protocol — not implemented" },
  // Fantech WG14P is auto-listed from the @openmouse/protocol driver registry.
  { brand: "Cooler Master", model: "MasterMouse MM720", status: "driver",    req: 1,
    note: "CM protocol — not implemented" },
  { brand: "Cooler Master", model: "MM711",             status: "driver",    req: 1,
    note: "CM protocol — not implemented" },
  { brand: "K-snake",     model: "X11",               status: "driver",    req: 1,
    note: "VID 0xA8A4 (USB) / 0xA8A5 (2.4G) PID 0x2255 — 0x55-framed output-report protocol, vendor panel reverse-engineered, driver in progress in mouse-protocol" },

  // UNKNOWNS ────────────────────────────────────────────────────────────
  { brand: "Hitscan",       model: "Hyperlight",        status: "unknown",   req: 5,
    note: "Protocol unknown — HID capture needed" },
  { brand: "RAWM",          model: "Leviathan V4",      status: "unknown",   req: 5,
    note: "Protocol unknown" },
  { brand: "AJAZZ",         model: "AJ159 Apex",        status: "unknown",   req: 5,
    note: "Protocol unknown" },
  { brand: "Furycube",      model: "G11",               status: "unknown",   req: 5,
    note: "Protocol unknown" },
  { brand: "Mchose",        model: "A7 V2 Ultra+",      status: "supported", req: 0,
    pids: [0x4021, 0x100b],
    note: "Confirmed on hardware over both the 2.4 GHz receiver and the cable — model, firmware, battery and charge state, DPI stages and values, stage count, polling, lift-off, motion sync, ripple, angle snapping, angle tuning, performance mode, debounce, sleep, 3 named profiles and button remapping all round-tripped" },
  { brand: "Mchose",        model: "MagDock (charging base)", status: "supported", req: 0,
    pids: [0x1012],
    note: "The A7 V2 base, not a mouse -- RGB read and write confirmed on hardware; the mice themselves have no LEDs" },
  { brand: "Mchose",        model: "A7 V2 Ultra",       status: "likely",    req: 0,
    note: "Same driver and protocol as the Ultra+; not confirmed on hardware" },
  { brand: "Mchose",        model: "A7 V2 Pro+",        status: "likely",    req: 0,
    note: "Same driver and protocol as the Ultra+; not confirmed on hardware" },
  { brand: "Mchose",        model: "A7 V2 Pro",         status: "likely",    req: 0,
    note: "Same driver and protocol as the Ultra+; not confirmed on hardware" },
  { brand: "Mchose",        model: "K7 Ultra",          status: "unknown",   req: 5,
    note: "Protocol unknown" },
  { brand: "Mchose",        model: "L7 Ultra+",         status: "unknown",   req: 3,
    note: "Protocol unknown" },
  { brand: "G-Wolves",      model: "HTX Mini 8K",       status: "unknown",   req: 3,
    note: "Protocol unknown" },
  { brand: "Angry Miao",    model: "Infinity .97",      status: "unknown",   req: 3,
    note: "Protocol unknown" },
  { brand: "Dark Project",  model: "Novus SE",          status: "unknown",   req: 2,
    note: "Protocol unknown — HID capture needed" },
  { brand: "Scyrox",        model: "V8",                status: "unknown",   req: 2,
    note: "Protocol unknown" },
  { brand: "Incott",        model: "G23 V2 Pro",        status: "unknown",   req: 2,
    note: "Protocol unknown" },
  { brand: "Mchose",        model: "AX5",               status: "unknown",   req: 2,
    note: "Protocol unknown" },
  { brand: "AJAZZ",         model: "AJ139 Pro",         status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "AJAZZ",         model: "AJ199",             status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "Gravastar",     model: "Mercury X Pro",     status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "Gravastar",     model: "M1",                status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "Gravastar",     model: "M2",                status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "G-Wolves",      model: "HT-M-H ACE Wireless",status: "unknown", req: 1,
    note: "Protocol unknown" },
  { brand: "Angry Miao",    model: "Infinity Mouse",    status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "VortexSeries",  model: "IGNIX F3",          status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "Darmoshark",    model: "M3S",               status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "RAWM",          model: "MH01 Pro",          status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "Swiftpoint",    model: "Z2",                status: "unknown",   req: 1,
    note: "Has own software — complex macro/haptics protocol" },
  { brand: "Swiftpoint",    model: "Z3",                status: "unknown",   req: 1,
    note: "Has own software — complex macro/haptics protocol" },
  { brand: "Kreo",          model: "Chimera V2 Wireless",status: "unknown",  req: 1,
    note: "Protocol unknown" },
  { brand: "Kreo",          model: "Harpy",             status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "ipi",           model: "Float 3950",        status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "Solakaka",      model: "SM802 Pro",         status: "unknown",   req: 1,
    note: "Has its own web configurator" },
  { brand: "E-YOOSO",       model: "X-44 Lite",         status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "HAVIT",         model: "Gamenote",          status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "Empire Gaming", model: "RF906 Wireless",    status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "DeadSkull",     model: "Orbit Wired",       status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "ISY",           model: "IGM-6000",          status: "unknown",   req: 1,
    note: "Protocol unknown" },
];
